name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      # Checkout du code avec tout l’historique pour SonarCloud
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Analyse SonarCloud
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=shop_management
            -Dsonar.organization=oumaimaboullam
            -Dsonar.branch.name=main
            -Dsonar.projectBaseDir=.
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}